### ISSUE TITLE
sticky: successively changing the font size deactivates the function itself.

### ISSUE THREAD

**Issue by haggen88** [linuxmint/mint20.3-beta#20] opened 2021-12-15 01:07 UTC
Successively changing the font size disables this function.  At one point changes of font size are not registered.

Steps to reproduce

1-create new note
2-write a line with the default font size
3-write another line with a smaller font size
4-write another line with a larger font size
5-write another line with a larger size than the previous one

---
Console output :

mint@mint:~$ sticky
Traceback (most recent call last):
  File "/usr/lib/sticky/note_buffer.py", line 613, in do_insert_text
    if location.has_tag(self.get_tag_table().lookup(tag_name)):
TypeError: Argument 1 does not allow None as a value
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_lib_sticky_sticky.py.999.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/sticky/note_buffer.py", line 613, in do_insert_text
    if location.has_tag(self.get_tag_table().lookup(tag_name)):
TypeError: Argument 1 does not allow None as a value
Traceback (most recent call last):
  File "/usr/lib/sticky/note_buffer.py", line 613, in do_insert_text
    if location.has_tag(self.get_tag_table().lookup(tag_name)):
TypeError: Argument 1 does not allow None as a value
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_lib_sticky_sticky.py.999.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/sticky/note_buffer.py", line 613, in do_insert_text
    if location.has_tag(self.get_tag_table().lookup(tag_name)):
TypeError: Argument 1 does not allow None as a value
Traceback (most recent call last):
  File "/usr/lib/sticky/note_buffer.py", line 613, in do_insert_text
    if location.has_tag(self.get_tag_table().lookup(tag_name)):
TypeError: Argument 1 does not allow None as a value
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_lib_sticky_sticky.py.999.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/sticky/note_buffer.py", line 613, in do_insert_text
    if location.has_tag(self.get_tag_table().lookup(tag_name)):
TypeError: Argument 1 does not allow None as a value
Traceback (most recent call last):
  File "/usr/lib/sticky/note_buffer.py", line 613, in do_insert_text
    if location.has_tag(self.get_tag_table().lookup(tag_name)):
TypeError: Argument 1 does not allow None as a value
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_lib_sticky_sticky.py.999.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/sticky/note_buffer.py", line 613, in do_insert_text
    if location.has_tag(self.get_tag_table().lookup(tag_name)):
TypeError: Argument 1 does not allow None as a value
Traceback (most recent call last):
  File "/usr/lib/sticky/note_buffer.py", line 613, in do_insert_text
    if location.has_tag(self.get_tag_table().lookup(tag_name)):
TypeError: Argument 1 does not allow None as a value
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_lib_sticky_sticky.py.999.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/sticky/note_buffer.py", line 613, in do_insert_text
    if location.has_tag(self.get_tag_table().lookup(tag_name)):
TypeError: Argument 1 does not allow None as a value
Traceback (most recent call last):
  File "/usr/lib/sticky/note_buffer.py", line 613, in do_insert_text
    if location.has_tag(self.get_tag_table().lookup(tag_name)):
TypeError: Argument 1 does not allow None as a value
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_lib_sticky_sticky.py.999.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/sticky/note_buffer.py", line 613, in do_insert_text
    if location.has_tag(self.get_tag_table().lookup(tag_name)):
TypeError: Argument 1 does not allow None as a value
Traceback (most recent call last):
  File "/usr/lib/sticky/note_buffer.py", line 613, in do_insert_text
    if location.has_tag(self.get_tag_table().lookup(tag_name)):
TypeError: Argument 1 does not allow None as a value
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_lib_sticky_sticky.py.999.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/sticky/note_buffer.py", line 613, in do_insert_text
    if location.has_tag(self.get_tag_table().lookup(tag_name)):
TypeError: Argument 1 does not allow None as a value
Traceback (most recent call last):
  File "/usr/lib/sticky/note_buffer.py", line 613, in do_insert_text
    if location.has_tag(self.get_tag_table().lookup(tag_name)):
TypeError: Argument 1 does not allow None as a value
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_lib_sticky_sticky.py.999.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/sticky/note_buffer.py", line 613, in do_insert_text
    if location.has_tag(self.get_tag_table().lookup(tag_name)):
TypeError: Argument 1 does not allow None as a value
Traceback (most recent call last):
  File "/usr/lib/sticky/note_buffer.py", line 613, in do_insert_text
    if location.has_tag(self.get_tag_table().lookup(tag_name)):
TypeError: Argument 1 does not allow None as a value
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_lib_sticky_sticky.py.999.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/sticky/note_buffer.py", line 613, in do_insert_text
    if location.has_tag(self.get_tag_table().lookup(tag_name)):
TypeError: Argument 1 does not allow None as a value
Traceback (most recent call last):
  File "/usr/lib/sticky/note_buffer.py", line 613, in do_insert_text
    if location.has_tag(self.get_tag_table().lookup(tag_name)):
TypeError: Argument 1 does not allow None as a value
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_lib_sticky_sticky.py.999.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/sticky/note_buffer.py", line 613, in do_insert_text
    if location.has_tag(self.get_tag_table().lookup(tag_name)):
TypeError: Argument 1 does not allow None as a value
Traceback (most recent call last):
  File "/usr/lib/sticky/note_buffer.py", line 613, in do_insert_text
    if location.has_tag(self.get_tag_table().lookup(tag_name)):
TypeError: Argument 1 does not allow None as a value
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_lib_sticky_sticky.py.999.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/sticky/note_buffer.py", line 613, in do_insert_text
    if location.has_tag(self.get_tag_table().lookup(tag_name)):
TypeError: Argument 1 does not allow None as a value
Traceback (most recent call last):
  File "/usr/lib/sticky/note_buffer.py", line 613, in do_insert_text
    if location.has_tag(self.get_tag_table().lookup(tag_name)):
TypeError: Argument 1 does not allow None as a value
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_lib_sticky_sticky.py.999.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/sticky/note_buffer.py", line 613, in do_insert_text
    if location.has_tag(self.get_tag_table().lookup(tag_name)):
TypeError: Argument 1 does not allow None as a value
Traceback (most recent call last):
  File "/usr/lib/sticky/note_buffer.py", line 613, in do_insert_text
    if location.has_tag(self.get_tag_table().lookup(tag_name)):
TypeError: Argument 1 does not allow None as a value
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_lib_sticky_sticky.py.999.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/sticky/note_buffer.py", line 613, in do_insert_text
    if location.has_tag(self.get_tag_table().lookup(tag_name)):
TypeError: Argument 1 does not allow None as a value
Traceback (most recent call last):
  File "/usr/lib/sticky/note_buffer.py", line 613, in do_insert_text
    if location.has_tag(self.get_tag_table().lookup(tag_name)):
TypeError: Argument 1 does not allow None as a value
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_lib_sticky_sticky.py.999.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/sticky/note_buffer.py", line 613, in do_insert_text
    if location.has_tag(self.get_tag_table().lookup(tag_name)):
TypeError: Argument 1 does not allow None as a value
Traceback (most recent call last):
  File "/usr/lib/sticky/note_buffer.py", line 613, in do_insert_text
    if location.has_tag(self.get_tag_table().lookup(tag_name)):
TypeError: Argument 1 does not allow None as a value
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_lib_sticky_sticky.py.999.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/sticky/note_buffer.py", line 613, in do_insert_text
    if location.has_tag(self.get_tag_table().lookup(tag_name)):
TypeError: Argument 1 does not allow None as a value
Traceback (most recent call last):
  File "/usr/lib/sticky/note_buffer.py", line 613, in do_insert_text
    if location.has_tag(self.get_tag_table().lookup(tag_name)):
TypeError: Argument 1 does not allow None as a value
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_lib_sticky_sticky.py.999.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/sticky/note_buffer.py", line 613, in do_insert_text
    if location.has_tag(self.get_tag_table().lookup(tag_name)):
TypeError: Argument 1 does not allow None as a value
Traceback (most recent call last):
  File "/usr/lib/sticky/note_buffer.py", line 613, in do_insert_text
    if location.has_tag(self.get_tag_table().lookup(tag_name)):
TypeError: Argument 1 does not allow None as a value
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_lib_sticky_sticky.py.999.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/sticky/note_buffer.py", line 613, in do_insert_text
    if location.has_tag(self.get_tag_table().lookup(tag_name)):
TypeError: Argument 1 does not allow None as a value
Traceback (most recent call last):
  File "/usr/lib/sticky/note_buffer.py", line 613, in do_insert_text
    if location.has_tag(self.get_tag_table().lookup(tag_name)):
TypeError: Argument 1 does not allow None as a value
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_lib_sticky_sticky.py.999.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/sticky/note_buffer.py", line 613, in do_insert_text
    if location.has_tag(self.get_tag_table().lookup(tag_name)):
TypeError: Argument 1 does not allow None as a value
Traceback (most recent call last):
  File "/usr/lib/sticky/note_buffer.py", line 613, in do_insert_text
    if location.has_tag(self.get_tag_table().lookup(tag_name)):
TypeError: Argument 1 does not allow None as a value
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_lib_sticky_sticky.py.999.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/sticky/note_buffer.py", line 613, in do_insert_text
    if location.has_tag(self.get_tag_table().lookup(tag_name)):
TypeError: Argument 1 does not allow None as a value
Traceback (most recent call last):
  File "/usr/lib/sticky/note_buffer.py", line 613, in do_insert_text
    if location.has_tag(self.get_tag_table().lookup(tag_name)):
TypeError: Argument 1 does not allow None as a value
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_lib_sticky_sticky.py.999.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/sticky/note_buffer.py", line 613, in do_insert_text
    if location.has_tag(self.get_tag_table().lookup(tag_name)):
TypeError: Argument 1 does not allow None as a value

---

[sticky - xsession-errors.zip](https://github.com/linuxmint/mint20.3-beta/files/7721326/sticky.-.xsession-errors.zip)

---

https://user-images.githubusercontent.com/68134588/146230821-d153991a-b98a-4ba7-87f0-7a8a571a3c8d.mp4

---
PS. A proposal for a new icon:  [Sticky.Note_draft.zip](https://github.com/linuxmint/mint20.3-beta/files/7720684/Sticky.Note_draft.zip)

**Comment by WhosyVox** [comment] 2021-12-15 15:52
So for the error message above, it appears the issue is a lack of definition for the 'normal' tag in the table at `note_buffer.py:6`

It's not the only issue though as fixing this (and thus the error printed in console) does not fix every issue in changing font size.
The program acknowledges that it should be printing in small at around line 613 of the same file, but no tag is applied. This is also reflected in the notes.json store.

That's as far as I can debug though. I'm not fluent in Python.

**Comment by collinss** [comment] 2021-12-16 22:50
This should be fixed now.

@haggen88 btw, those icons are definitely better than what we have currently. Could you submit a pull request to change it? The ugly purple one that I made is at https://github.com/linuxmint/sticky/blob/master/usr/share/icons/hicolor/scalable/apps/sticky.svg. If you replace that, then we can patch the mint icon themes to remove the symlinks to the other ugly icons.

**Closed as completed by collinss** 2021-12-16 22:50 UTC

**Comment by clefebvre** [comment] 2021-12-17 11:51
Fixed in sticky 1.5.
