### ISSUE TITLE
mintwelcome: uses a different theme than the system

### ISSUE THREAD

**Issue by Ethanol6** [linuxmint/mint20.3-beta#39] opened 2021-12-17 21:44 UTC
Mint 20.3
Cinnamon 5.2.6
Muffin 5.2.0

When going through the Mint Welcome "First Steps", applications launched from within have a different Window Border theme than the Mint Welcome window. Between the two options available for Window Borders themes, Mint-Y and Mint-X, the one used by other applications is not either one of those options.

## Steps to reproduce:
Install Mint 20.3 beta Cinnamon edition
Open an application from Mint Welcome -> First Steps by clicking "launch"

## Expected behaviour:
Window Borders theme of other apps should be the same as the Mint Welcome default.

[https://github.com/Ethanol6/mintBetaTesting/raw/main/WindowButtons203BetaCinnamon.png](https://github.com/Ethanol6/mintBetaTesting/raw/main/WindowButtons203BetaCinnamon.png)

## Fix:
Manually select "Mint-Y" from the Window Borders options from System Settings.

**Comment by mtwebster** [comment] 2021-12-22 18:46
I can't reproduce this - I'm not even sure what theme that is. Do you have any other themes installed?

**Comment by Ethanol6** [comment] 2021-12-23 03:11
> I can't reproduce this - I'm not even sure what theme that is. Do you have any other themes installed?

No extra themes. This was a clean install, just going through the Welcome for the first time after installation.

**Comment by clefebvre** [comment] 2022-01-02 10:41
Afaik it was fixed by https://github.com/linuxmint/mintwelcome/commit/8544814a4bc1766536623319dc81f6725702cf62.

To reproduce, switch to dark using mintwelcome and then choose modern or traditional.

**Closed as completed by clefebvre** 2022-01-02 10:41 UTC
