### ISSUE TITLE
mate/xfce: alt+Print doesn't work

### ISSUE THREAD

**Issue by orcus-de** [linuxmint/mint20.3-beta#54] opened 2021-12-20 13:20 UTC
mint 20.3 beta - mate (only) - bug: alt+Print not working - workaround

Mate fully updated at 2021-12-20 13:57 CET+1

The default keyboad shortcut to take a screen shot of the **active window** using **Alt+Print** is not working.

Notes:
1) The issue shows up with mate 20.2 too (could even be longer around).

2) Taking a screen shot of the entire desktop using Print key alone is working.

3) Trying to re-assign Alt-Print again is denied by Keyboard Shortcuts tool - seemingly some conflict with with other tooling gnome/cinnamon -> see details below

Steps to reproduce

1) grab a current copy of dconf settings:
`gsettings list-recursively >a.txt`

2) try using alt+Print - not working

3) Workaround: use keyboard shortcuts tool and define (for example) Shift+Print taking screen shots of active window - starts working.

4) grab modified dconf settings
` gsettings list-recursively >b.txt`

Details - deconf settings  before/after setting up new short-cut:
```

demo@20-3-beta-mate:~$ diff a.txt b.txt 
1621c1621
< com.linuxmint.mintmenu.plugins.applications last-active-tab 0
---
> com.linuxmint.mintmenu.plugins.applications last-active-tab 1
2345c2345
< org.mate.screenshot last-save-directory ''
---
> org.mate.screenshot last-save-directory 'file:///home/demo/Desktop'
2490c2490
< org.mate.Marco.global-keybindings run-command-window-screenshot '<Alt>Print'
---
> org.mate.Marco.global-keybindings run-command-window-screenshot '<Shift>Print'

# search for conflicting dconf settings
# before setting new short-cut
demo@20-3-beta-mate:~$ grep '<Alt>Print'  a.txt 
org.cinnamon.desktop.keybindings.media-keys window-screenshot ['<Alt>Print']
org.cinnamon.desktop.keybindings.media-keys window-screenshot-clip ['<Control><Alt>Print']
org.gnome.settings-daemon.plugins.media-keys window-screenshot-clip ['<Ctrl><Alt>Print']
org.gnome.settings-daemon.plugins.media-keys window-screenshot ['<Alt>Print']
org.mate.Marco.global-keybindings run-command-window-screenshot '<Alt>Print'

# adter setting new short-cut
demo@20-3-beta-mate:~$ grep '<Alt>Print'  b.txt 
org.cinnamon.desktop.keybindings.media-keys window-screenshot ['<Alt>Print']
org.cinnamon.desktop.keybindings.media-keys window-screenshot-clip ['<Control><Alt>Print']
org.gnome.settings-daemon.plugins.media-keys window-screenshot-clip ['<Ctrl><Alt>Print']
org.gnome.settings-daemon.plugins.media-keys window-screenshot ['<Alt>Print']
```

**Comment by Jildridge** [comment] 2021-12-20 14:02
Hi,
That is strange. Alt+print is working neither with my mate-20.3-beta version; however I never tested this shortcut earlier since I usually simply use the print-key for screenshots. And print-key only is working on my beta.

**Comment by mtwebster** [comment] 2021-12-22 18:37
I can't reproduce this - if you have 2 alt keys, does this happen with either? Are you trying this in a virtual machine or real hardware?

**Comment by orcus-de** [comment] 2021-12-23 01:17
mint 20.3 beta - mate (only) - bug: alt+Print not working - workaround
(edit: fixed wrong labled cmd-line prompts to avoid confusion)

see below Test 3), Note (2b) might help to pin-point some conflict ...

As I'm using a german keyboard normally (just to exlude its the reason) - I created a complete fresh VM again using (almost everywhere) default options:

VM-Setup
- qemu/kvm vm:
- 4 GiB Ram
- 15 GiB vdisk size
- bios-install

modifications vs defaults:
- added RNG device (which is always missing with the default setup done by virtmanager)
- using virtio instead of QXL video

VM-Install using default options:

- linuxmint-20.3-mate-64bit-beta.iso

- english gui
- en-US keyboard layout
- no multimedia packages installed
- default timezone - Berlin (in my case) accepted
- added user with password + login requirement

Test 1) fresh install - no updates installed - no additional sofware installed

Running vm in full-screen mode (to minimize potential impact of host-os):
Testing left-Alt+ PrtScrn - not working
Testing right-Alt+ PrtScrn - not working

running: tail -f ~/.xsession-errors # shows no new errors/messages coming up
running: xev    # (at vm) while testing keys - shows press+release events for both variants
running: xev    # (at host) while testing keys - shows NO press+release events for both variants


Note(1): as its been supected(?) that the vm could be the reason = host (19.3 cinnamon ) would intercept/steal events:

a) running vm in regular size + having focus
Alt-print is NOT handled by the host (xev running at the host shows NO keyboard event) + there are still keyboard events shown at the xev output of the vm (as expected). - no screenshot taken neither at host nor at vm


b) running vm in regular size + switching focus away from the vm to another window of the host install 
Alt-print is handled by the  host (xev running at the host shows keyboard event) + there are NO keyboard events shown at the xev output of the vm (as expected) - host takes screenshot - no screenshot taken at vm.

Current dconf settings of the default-setup - see alt-print-info-github-01.txt below

Test 2)
installed available updates - thursday 2021-12-23  CET +1  01:08 am
staying with default mirrors (not switching to local ones)
reboot

identical outcome ...
Running vm in full-screen mode (to minimize potential impact of host-os):
Testing left-Alt+ PrtScrn - not working
Testing right-Alt+ PrtScrn - not working

running: tail -f ~/.xsession-errors # show no new errors/messages coming up
running: xev    # (at vm) while testing keys - shows press+release events for both variants
running: xev    # (at host) while testing keys - shows NO press+release events for both variants

Current dconf settings of the modified-setup - alt-print-info-github-02.txt (using Shift+Print)

Test 3) - using:
keyboard shortcuts tool from main-menu to assing different shortcut for
"Take a screenshot of a window" - using this shortcuts (Mod4=Windows-key):

Shift+Print - is working // vm xev shows events - host xev show no events
Ctrl+Print  - is working ....
Mod4+Print  - is working
Shift+P     - is working
Alt+P       - is working
Ctrl+P      - is working

Note (2)
a) keyboard shortcuts tool doesn't differentiate between left/right ctrl or shift (at least according to dconf settings)

b) after having switched to a different short-cut one isn't able to re-assign Alt+Print again as a shortcut - not matter if there is an actual replacement defined or if one deleted/disabled the current one using Backspace == **there is something explicitly dening to reuse Alt+Print as a shortcut again**

Modified dconf settings (updates installed - having Shift+Print assigned including diffs)
see alt-print-info-github-02.txt below


**alt-print-info-github-01.txt:**
```
# dconf settings bindings for '<Alt>Print' / original values

oadm@mint-20-3-beta-mate:~$ gsettings list-recursively | grep '<Alt>Print' >alt-print-binding-01.txt

oadm@mint-20-3-beta-mate:~$ cat alt-print-binding-01.txt 
org.cinnamon.desktop.keybindings.media-keys window-screenshot ['<Alt>Print']
org.cinnamon.desktop.keybindings.media-keys window-screenshot-clip ['<Control><Alt>Print']
org.gnome.settings-daemon.plugins.media-keys window-screenshot-clip ['<Ctrl><Alt>Print']
org.gnome.settings-daemon.plugins.media-keys window-screenshot ['<Alt>Print']
org.mate.Marco.global-keybindings run-command-window-screenshot '<Alt>Print'

oadm@mint-20-3-beta-mate:~$ gsettings list-recursively >dconf-settings-01.txt # to diff later on

```

**alt-print-info-github-02.txt:**
```
# dconf settings bindings for '<Shift>Print' / updated values + diff original vs modified

oadm@mint-20-3-beta-mate:~$ gsettings list-recursively | grep '<Alt>Print' >alt-print-binding-02.txt

oadm@mint-20-3-beta-mate:~$ cat alt-print-binding-02.txt
org.cinnamon.desktop.keybindings.media-keys window-screenshot ['<Alt>Print']
org.cinnamon.desktop.keybindings.media-keys window-screenshot-clip ['<Control><Alt>Print']
org.gnome.settings-daemon.plugins.media-keys window-screenshot-clip ['<Ctrl><Alt>Print']
org.gnome.settings-daemon.plugins.media-keys window-screenshot ['<Alt>Print']

oadm@mint-20-3-beta-mate:~$ diff alt-print-binding-01.txt alt-print-binding-02.txt
5d4
< org.mate.Marco.global-keybindings run-command-window-screenshot '<Alt>Print'


# diff complete dconf settings - original vs update + modified
oadm@mint-20-3-beta-mate:~$ diff dconf-settings-01.txt dconf-settings-02.txt 
538c538
< com.linuxmint.updates window-pane-position 344
---
> com.linuxmint.updates window-pane-position 303
547c547
< com.linuxmint.updates show-welcome-page true
---
> com.linuxmint.updates show-welcome-page false
550,551c550,551
< com.linuxmint.updates default-repo-is-ok false
< com.linuxmint.updates install-last-run 0
---
> com.linuxmint.updates default-repo-is-ok true
> com.linuxmint.updates install-last-run 1640218179
553c553
< com.linuxmint.updates refresh-last-run 1640216637
---
> com.linuxmint.updates refresh-last-run 1640219464
1518c1518
< org.gtk.Settings.FileChooser window-position (-1, -1)
---
> org.gtk.Settings.FileChooser window-position (0, 0)
1521c1521
< org.gtk.Settings.FileChooser window-size (-1, -1)
---
> org.gtk.Settings.FileChooser window-size (1022, 710)
1714c1714
< org.mate.caja.window-state geometry ''
---
> org.mate.caja.window-state geometry '800x550+111+80'
2372c2372
< org.x.editor.state.window side-panel-active-page 0
---
> org.x.editor.state.window side-panel-active-page 827629879
2374,2375c2374,2375
< org.x.editor.state.window size (650, 500)
< org.x.editor.state.window state 0
---
> org.x.editor.state.window size (903, 500)
> org.x.editor.state.window state 128
2490c2490
< org.mate.Marco.global-keybindings run-command-window-screenshot '<Alt>Print'
---
> org.mate.Marco.global-keybindings run-command-window-screenshot '<Shift>Print'
2559c2559
< org.mate.session session-start 1640216010
---
> org.mate.session session-start 1640218841
oadm@mint-20-3-beta-mate:~$ 

```

**Comment by orcus-de** [comment] 2021-12-23 12:41
likely the underlying reason: Alt+Print collides seemingly with the Magic Sysrequest at Mate
**edit: identical issue with xfce (tested afterwards)  + might be related: use a regular keyboard, not some laptop-kbd**


see https://bugs.launchpad.net/ubuntu/+source/metacity/+bug/642792

test/workaround (although I prefer to have the magic sysrequest enabled myself)
use: sudo sysctl -w kernel.sysrq=0

after that
1) "Take a screenshot of a window" with default Alt+Print starts working
2) one is able to re-assign the shortcut again (not blocked any longer), no matter if there has been a different shortcut assigned in between or the shortcut has been disable by using backspace before

Note: re-assigning the shortcut key will be denoted as Alt+SysReq  - but is still working
___
PS: enjoy your holidays

**Comment by clefebvre** [comment] 2022-01-02 11:24
wow, what a mess.

I can't reproduce this here. Even in a virtualbox VM Alt+PrintScreen works for me. That said, I think the type of keyboard and the locale play a role here. I'm using an ANSI keyboard in en_US configuration.

Note the difference also between Alt and Alt-Gr on some configurations. Alt isn't supposed to modify a key event at keyboard level, but Alt_Gr is.

I'll close this here for now since it's both upstream and not a 20.3 regression.

**Closed as completed by clefebvre** 2022-01-02 11:24 UTC
