### ISSUE TITLE
nemo: Right-Menu Duplicate on a text file creates an empty text file.

### ISSUE THREAD

**Issue by Ne2hpmbw** [linuxmint/mint20.3-beta#70] opened 2021-12-29 07:51 UTC
**Steps to reproduce**
Happens 100% of the time when using the Right-Menu Duplicate on a plain text file. A copy of the text file will be created but all the contents are blank.

**Expected behavior**
A duplicate (i.e., a copy) of a text file that has all the same contents as the original.

**Comment by WhosyVox** [comment] 2021-12-29 11:16
Have you made any modifications to Nemo beyond enabling the Duplicate context menu entry?
I've tried to verify this but have been unable to; all duplicate text documents I've created have also had the contents duplicated as you would expect.
This has been tested in a fresh and updated version of Mint 20.3 beta Cinnamon.

If you run Nemo via terminal, do you get any errors printed when attempting a duplicate?

**Comment by xenopeek** [comment] 2021-12-30 08:47
I also can't reproduce this issue by doing right-click>Duplicate (after enabling that in Preferences) or Edit>Duplicate with a plain text file selected.

Steps I tried:

1. Right-click empty spot in Nemo and select Create New Document>Empty Document
2. Give the new file a name, double-click to open it in Xed and put some text ("hello world") in it and save & close
3. Right-click the new file and select Duplicate
4. Check the "new file (copy)" file that was created, it has the same text in it

@Ne2hpmbw please try the suggestion to run Nemo from terminal to maybe get any errors there, and try the above 4 steps. To do so, open Terminal from your menu and first type `nemo -q` to close any running Nemo process and then type `nemo` to open Nemo anew. Any errors and warnings are shown on the terminal. Try the right-click>Duplicate on a file and see if any output is on the terminal. If yes, copy that and share here (you can select all and copy text from the terminal through its Edit menu). Afterwards close Nemo and that should unblock the terminal so you can also close that.

Anything special about your installation? Like are the files you're trying to duplicate on a filesystem other than ext4?

**Comment by Ne2hpmbw** [comment] 2021-12-31 02:26
Thank you very much for your suggestions and help!

I did all the suggestions and still always get the same problem: the duplicate text file is empty inside (please note that there never any problems duplicating any other type of file).

I did get the following error messages in my Terminal window after doing all the steps:

(nemo:29859): Gtk-WARNING **: 18:18:36.920: Failed to register client: GDBus.Error:org.gnome.SessionManager.AlreadyRegistered: Unable to register client
nemo-media-columns: using a timeout of 0.20 second(s) for file processing
jr@ASUS-Laptop:~$ nemo

(nemo:29974): Gtk-WARNING **: 18:19:20.624: Failed to register client: GDBus.Error:org.gnome.SessionManager.AlreadyRegistered: Unable to register client
nemo-media-columns: using a timeout of 0.20 second(s) for file processing

**Comment by Ne2hpmbw** [comment] 2021-12-31 02:30
Here is a screenshot of my Xed Prefaces (thank you very much again):

![2021_12_30_Xed_Prefaces](https://user-images.githubusercontent.com/73332339/147799596-dd5816dd-90f1-4420-89ce-881a6d1deaab.png)


![image](https://user-images.githubusercontent.com/73332339/147799612-857b6165-765f-483b-99cd-97b185fdaf36.png)

**Comment by Ne2hpmbw** [comment] 2021-12-31 03:29
Here is a screenshot of my Nemo Prefaces (thank you very much again):
![2021_12_30_Nemo_Prefaces](https://user-images.githubusercontent.com/73332339/147801532-91129d16-5156-4964-96fe-87c28ab2eb03.png)

**Comment by WhosyVox** [comment] 2021-12-31 17:52
@Ne2hpmbw It seems like you might have various plugins active, based on the terminal output (nemo-media-columns for example).

As we cannot seem to replicate this, the issue may lie in your particular setup.

Was this a fresh install of Mint 20.3 beta or did you upgrade from a previous version? Additionally, what plugins or third-party scripts do you have running on Nemo?

**Comment by xenopeek** [comment] 2021-12-31 19:36
Yes, a screenshot of the Nemo preferences > Plugins menu may be useful to try and figure out what in your setup may play a role in this.

**Comment by mtwebster** [comment] 2022-01-01 17:17
> (nemo:29859): Gtk-WARNING **: 18:18:36.920: Failed to register client: GDBus.Error:org.gnome.SessionManager.AlreadyRegistered: Unable to register client

That's a really weird message. Would you mind creating a new user account and testing this issue there?

**Comment by Ne2hpmbw** [comment] 2022-01-02 02:44
My two other user accounts (on the same computer) do NOT have the problem!
I tried again on my account, this time turning all Xed plugins OFF, and the problem still persists.

FYI, I was going to go through all the steps again and as soon as I opened up the Terminal and entered nemo -q and I immediately get the following error:

jr@ASUS-Laptop:~$ nemo -q

(nemo:11393): Gtk-WARNING **: 18:32:07.524: Failed to register client: GDBus.Error:org.gnome.SessionManager.AlreadyRegistered: Unable to register client
nemo-media-columns: using a timeout of 0.20 second(s) for file processing
jr@ASUS-Laptop:~$ 



I then went into Nemo and turned OFF the plugin for media columns

I then tried the Terminal again and again got an immediate (but slightly different) error:

jr@ASUS-Laptop:~$ nemo -q

(nemo:11943): Gtk-WARNING **: 18:36:17.344: Failed to register client: GDBus.Error:org.gnome.SessionManager.AlreadyRegistered: Unable to register client
jr@ASUS-Laptop:~$ 


I started nemo from the Termial and got the following error:

jr@ASUS-Laptop:~$ nemo

(nemo:12278): Gtk-WARNING **: 18:38:54.828: Failed to register client: GDBus.Error:org.gnome.SessionManager.AlreadyRegistered: Unable to register client

Then the Nemo file manager opened.

Created another text file per the steps, etc.

Same problem.

However, there were two (2) additional error messages in the Terminal regarding file metadata:


jr@ASUS-Laptop:~$ nemo

(nemo:12278): Gtk-WARNING **: 18:38:54.828: Failed to register client: GDBus.Error:org.gnome.SessionManager.AlreadyRegistered: Unable to register client

** (xed:13104): WARNING **: 18:41:29.762: Set document metadata failed: Error setting file metadata: No such file or directory

** (xed:13104): WARNING **: 18:41:29.762: Set document metadata failed: Error setting file metadata: No such file or directory



Any additional ideas or suggestions would be greatly appreciated!

Thank you very much!

**Comment by smurphos** [comment] 2022-01-02 07:20
As a hunch check your home for files not owned by your user (there shouldn't be any) - this command run in a terminal will list any problematic files - `find $HOME ! -user $USER`

**Comment by Ne2hpmbw** [comment] 2022-01-02 10:12
Nothing came back:

jr@ASUS-Laptop:~$ find $HOME ! -user $USER
jr@ASUS-Laptop:~$

**Comment by clefebvre** [comment] 2022-01-02 10:21
Closing since no bug is identified yet. I'd suggest to use the forums to troubleshoot. If you do find a bug in nemo please report it at github.com/linuxmint/nemo.

**Closed as completed by clefebvre** 2022-01-02 10:21 UTC
Labels: question

**Comment by Ne2hpmbw** [comment] 2022-01-02 10:22
Thank you.
