### ISSUE TITLE
Firefox - LM MATE: The dark firefox theme leaves some sharp corners behind the rounded corners of the MATE Mint-Y/Mint-Y Dark theme.

### ISSUE THREAD

**Issue by haggen88** [linuxmint/mint20.3-beta#62] opened 2021-12-23 15:45 UTC
@mtwebster 
It is the same problem [#5] but only occurs with the dark Firefox theme in LM MATE
 

Steps to reproduce:

1) Open Firefox
2) Switch to Firefox Dark theme
3) Customize toolbar and remove 'Title bar'.

![Screenshot at 2021-12-23 15-01-24](https://user-images.githubusercontent.com/68134588/147260458-ed248e38-e729-4188-8abf-4dfc3a1e3467.png)
![Screenshot at 2021-12-23 15-02-04](https://user-images.githubusercontent.com/68134588/147260471-a296e448-6b0d-41ea-9902-1b4973dae46f.png)

I tested this with the current iso and also after applying the available updates [including the new Firefox 95.0.1+linuxmint1.1+una].
The dark Firefox theme leaves those sharp corners regardless of the Mint-Y theme used in MATE. The Firefox Light theme does not present any problems.

![mate-frfx-light theme](https://user-images.githubusercontent.com/68134588/147261106-cab79416-6848-4484-ae68-24961c1f0f21.png)

The fix is apparently implemented only in Cinnamon: https://bugzilla.mozilla.org/show_bug.cgi?id=1746486

Regards

**Comment by mtwebster** [comment] 2021-12-23 16:43
The fix only affects Cinnamon because MATE and others are already treated correctly:
https://hg.mozilla.org/integration/autoland/diff/e4f54b8aab646425e35ab5a810cb1f3b73f72eca/widget/gtk/nsWindow.cpp

I can reproduce the dark theme issue in both Cinnamon and MATE in firefox 95.  Testing firefox 96b8 it appears to have been fixed:

https://www.dropbox.com/s/zda5k91fkdxhxzn/firefox_96.0b8%2Blinuxmint1%2Buna_amd64.deb?dl=0

Note: Only test this on a 20.3 system - it is the 'new' packaging. This won't include the aforementioned patch yet so you'll need to run with `GTK_CSD=1 firefox`. edit: I would also backup your .mozilla folder - if you try to downgrade back to 95 it will ditch your profile.

You'll also notice yet more changes to the titlebar buttons - no info on this yet..

**Comment by haggen88** [comment] 2021-12-23 21:02
@mtwebster  Thank you for explaining to me.

BTW...  I confirm the problem in LM Xfce 20.3. with Firefox 95.0.1+linuxmint1.1+una.  What is different is that when switching to the clear Firefox theme, sharp corners are also present.

![mynt darc-frfx darc](https://user-images.githubusercontent.com/68134588/147290608-58f05e59-198f-42f9-9899-392a0acd82f6.png)

![frfx l1ght-m1nt l1ght](https://user-images.githubusercontent.com/68134588/147291160-262d9502-40ce-432a-8410-c37cd0c3bbb1.png)

**Comment by clefebvre** [comment] 2021-12-27 12:10
Upstream. Will be fixed in Firefox 96.

**Closed as completed by clefebvre** 2021-12-27 12:10 UTC

**Comment by haggen88** [comment] 2021-12-27 13:38
@clefebvre @mtwebster  
I tested firefox 96 beta and now you see a small transparent area. I hope they fix it before the stable version.

![frfx 96 beta dark](https://user-images.githubusercontent.com/68134588/147476964-14b8620f-8f8a-4261-888e-8d36d754d28b.png)

![frfx 96 beta light](https://user-images.githubusercontent.com/68134588/147476971-3db6e5cd-bca9-4f4f-b206-28de68eb45f1.png)

Regards!
