### ISSUE TITLE
 "Fly" Effect is intuitive and Good when the Window is minimized to the panel

### ISSUE THREAD

**Issue by vegam57** [linuxmint/mint20.3-beta#56] opened 2021-12-20 20:42 UTC
This "Fly" Effect is intuitive and Good when the Window is minimized to the panel
If this is set as the factory default, isn't it possible to appeal the appeal of LM to new users with a fresh UX? 
Below is a trivial matter,
The opening and closing behavior of the drop-down list for Effect-type is unstable. 
![cinnamon-20211220-1](https://user-images.githubusercontent.com/78515193/146829016-0fbcd610-9f58-4c01-ab16-d39efc97c283.gif)

**Comment by clefebvre** [comment] 2021-12-27 12:07
It's a nice and clean effect alright. That's why it was left as a choice.

Could the dropdown list issue be a VM rendering bug? Is this a virtual machine?

**Comment by vegam57** [comment] 2021-12-27 12:50
This dropdown list issue  is on an intel real machine.

[code]
System:    Kernel: 5.4.0-91-generic x86_64 bits: 64 compiler: gcc v: 9.3.0 Desktop: Cinnamon 5.2.6 
           wm: muffin dm: LightDM Distro: Linux Mint 20.3 Una base: Ubuntu 20.04 focal 
Machine:   Type: Laptop System: Dell product: Latitude E6410 v: 0001 serial: <filter> Chassis: 
           type: 9 serial: <filter> 
           Mobo: Dell model: 04373Y v: A01 serial: <filter> BIOS: Dell v: A17 date: 05/12/2017 
Battery:   ID-1: BAT0 charge: 46.0 Wh condition: 46.0/48.8 Wh (94%) volts: 12.5/11.1 
           model: Samsung SDI DELL PT43699 serial: <filter> status: Full 
           Device-1: hidpp_battery_0 model: Logitech Wireless Mouse serial: <filter> 
           charge: 55% (should be ignored) status: Discharging 
CPU:       Topology: Dual Core model: Intel Core i5 M 520 bits: 64 type: MT MCP arch: Nehalem 
           rev: 5 L2 cache: 3072 KiB 
           flags: lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 19151 
           Speed: 1463 MHz min/max: 1199/2400 MHz Core speeds (MHz): 1: 1455 2: 1463 3: 1430 
           4: 1463 
Graphics:  Device-1: Intel Core Processor Integrated Graphics vendor: Dell Latitude E6410 
           driver: i915 v: kernel bus ID: 00:02.0 chip ID: 8086:0046 
           Display: x11 server: X.Org 1.20.13 driver: modesetting unloaded: fbdev,vesa 
           resolution: 1280x800~60Hz 
           OpenGL: renderer: Mesa DRI Intel HD Graphics (ILK) v: 2.1 Mesa 21.0.3 
           direct render: Yes 
Audio:     Device-1: Intel 5 Series/3400 Series High Definition Audio vendor: Dell Latitude E6410 
           driver: snd_hda_intel v: kernel bus ID: 00:1b.0 chip ID: 8086:3b56 
           Sound Server: ALSA v: k5.4.0-91-generic 
Network:   Device-1: Intel 82577LM Gigabit Network vendor: Dell Latitude E6410 driver: e1000e 
           v: 3.2.6-k port: 7040 bus ID: 00:19.0 chip ID: 8086:10ea 
           IF: eno1 state: down mac: <filter> 
           Device-2: Broadcom and subsidiaries BCM43224 802.11a/b/g/n 
           vendor: Dell Wireless 1520 Half-size Mini PCIe Card driver: bcma-pci-bridge v: N/A 
           port: 7000 bus ID: 02:00.0 chip ID: 14e4:4353 
           IF-ID-1: wlp2s0b1 state: up mac: <filter> 
Drives:    Local Storage: total: 114.80 GiB used: 10.15 GiB (8.8%) 
           ID-1: /dev/sda vendor: SanDisk model: SSD PLUS 120GB size: 111.80 GiB speed: 3.0 Gb/s 
           serial: <filter> 
           ID-2: /dev/sdb type: USB model: SafeNet eToken 7300 size: 3.00 GiB serial: <filter> 
Partition: ID-1: / size: 46.12 GiB used: 10.09 GiB (21.9%) fs: ext4 dev: /dev/sda6 
USB:       Hub: 1-0:1 info: Full speed (or root) Hub ports: 2 rev: 2.0 chip ID: 1d6b:0002 
           Hub: 1-1:2 info: Intel Integrated Rate Matching Hub ports: 6 rev: 2.0 
           chip ID: 8087:0020 
           Hub: 2-0:1 info: Full speed (or root) Hub ports: 2 rev: 2.0 chip ID: 1d6b:0002 
           Hub: 2-1:2 info: Intel Integrated Rate Matching Hub ports: 8 rev: 2.0 
           chip ID: 8087:0020 
           Device-1: 2-1.3:3 info: Logitech Unifying Receiver type: Keyboard,Mouse 
           driver: logitech-djreceiver,usbhid rev: 2.0 chip ID: 046d:c534 
           Device-2: 2-1.4:4 info: Aladdin Knowledge Systems type: Smart Card,HID,Mass Storage 
           driver: hid-generic,usb-storage,usbhid rev: 2.0 chip ID: 0529:0602 
           Device-3: 2-1.8:5 info: Broadcom BCM5880 Secure Applications Processor type: Smart Card 
           driver: N/A rev: 1.1 chip ID: 0a5c:5800 
Sensors:   System Temperatures: cpu: 49.0 C mobo: N/A sodimm: 29.0 C 
           Fan Speeds (RPM): cpu: 0 
Repos:     No active apt repos in: /etc/apt/sources.list 
           Active apt repos in: /etc/apt/sources.list.d/official-package-repositories.list 
           1: deb http: //packages.linuxmint.com una main upstream import backport #id:linuxmint_main
           2: deb http: //archive.ubuntu.com/ubuntu focal main restricted universe multiverse
           3: deb http: //archive.ubuntu.com/ubuntu focal-updates main restricted universe multiverse
           4: deb http: //archive.ubuntu.com/ubuntu focal-backports main restricted universe multiverse
           5: deb http: //security.ubuntu.com/ubuntu/ focal-security main restricted universe multiverse
           6: deb http: //archive.canonical.com/ubuntu/ focal partner
Info:      Processes: 225 Uptime: 11h 13m Memory: 5.73 GiB used: 1.56 GiB (27.2%) Init: systemd 
           v: 245 runlevel: 5 Compilers: gcc: 9.3.0 alt: 9 Client: Unknown python3.8 client 
           inxi: 3.0.38 
[/code]

**Comment by clefebvre** [comment] 2021-12-27 12:53
@vegam57 can you describe the issue? Sorry I don't really understand the problem.

**Comment by vegam57** [comment] 2021-12-27 13:09
Even if I open the dropdown list, it will close automatically.
Repeat it and it will start to stabilize.

**Comment by clefebvre** [comment] 2021-12-27 14:49
That's on any dropdowns? or just one in particular?

**Comment by vegam57** [comment] 2021-12-27 20:01
This is a common phenomenon in the behavior of Beta newly drop-down lists.
![スクリーンショット 2021-12-28 04-54-05](https://user-images.githubusercontent.com/78515193/147503459-b8fb47c5-b69e-40dd-9801-1be4dd3e1b59.png)

**Comment by mtwebster** [comment] 2021-12-28 03:50
Can you detail your language and region info?

Does this occur on other controls of that type on other cinnamon settings pages?

**Comment by vegam57** [comment] 2021-12-28 04:12
Hi,
Thank you for fixing Sticky to 1.6.
It's comfortable

Japanese Japan 

I had seen this only in the behavior of Beta newly drop-down lists.
No other controls of that type on other cinnamon settings pages had been seen.

However,It has been stable for the past few days.
I started to be optimistic that it was also generated in the cache?....

**Comment by mtwebster** [comment] 2021-12-28 18:51
If you create a new user and log into it, do you get the same issues with the dropdowns?

These ones you've noted are exactly the same as dropdowns (combo boxes) in all of the other cinnamon settings pages.

**Comment by vegam57** [comment] 2021-12-28 22:18
I created a new user and loged into it, saw the behavior.
It was already stable.

**Comment by mtwebster** [comment] 2021-12-29 19:44
I'm going to go ahead and close this, since you can no longer reproduce it and we never could.  If you do run into the issue again we can re-open this.

Thanks

**Closed as completed by mtwebster** 2021-12-29 19:44 UTC
