### ISSUE TITLE
Redshift often fails on its cold start

### ISSUE THREAD

**Issue by vegam57** [linuxmint/mint20.3-beta#60] opened 2021-12-21 21:45 UTC
Redshift often fails on its cold start
WiFi Ok
Network OK 
Not encountered in LM20.2 
![スクリーンショット 2021-12-19 06-29-48](https://user-images.githubusercontent.com/78515193/147001482-21961775-0af9-4c28-868e-94b551a7cbd2.png)

**Comment by LinuxOnTheDesktop** [comment] 2021-12-21 22:30
This problem has been around for some years. A bug report about it was filed against Cinnamon [here](https://github.com/linuxmint/cinnamon/issues/9772). That same report gives a workaround. The report was closed on the basis that the bug is a Redshift bug rather than a Mint bug. A bug is filed against Redshift - [here](https://github.com/jonls/redshift/issues/830). 

However, Redshift is - if I recall correctly - auto-enabled on Mint. So, it would be good for users of Mint were Redshift actually to work (work out of the box).

EDIT: I can't comment on the problem not appearing on Mint 20.2 and reappearing in 20.3. (For, I have long implemented the aforementioned workaround for the problem.)

**Comment by vegam57** [comment] 2021-12-22 06:33
Is that so.
I've understood the situation.
But in 20.2 I never had that failure on my PC.
Mystery.

**Comment by mtwebster** [comment] 2021-12-22 18:57
I can't reproduce this - does it happen every time?

**Comment by vegam57** [comment] 2021-12-22 19:12
No, it will occur with a probability of about 50%.
If it's an individual environment issue, please close it as my own issue .
Thank you.

**Comment by Mintulix** [comment] 2021-12-22 23:31
May be redshift starts a few milliseconds too early for the network. Try to add 1 second start delay. My settings in redshift.conf are without geoclue, so if you don't need it:
...
[redshift]
location-provider=manual
[manual]
lat=4.321  ; your location latitude
lon=1.234  ; your location longitude

**Comment by LinuxOnTheDesktop** [comment] 2021-12-22 23:40
> [Perhaps] redshift starts a few milliseconds too early for the network. Try to add 1 second start delay. My settings in redshift.conf are without geoclue [. .]

I suspect that the main issue here is something else. To wit: on Mint, and perhaps on other Linux distributions, it is always the case that Redshift's invocation of geoclue fails. EDIT: Or, yes, perhaps autostarting Redshift means that Redshift tries to use the network, via geoclue, before the network is available - I don't know.

**Comment by vegam57** [comment] 2021-12-23 01:19
> May be redshift starts a few milliseconds too early for the network. Try to add 1 second start delay. My settings in redshift.conf are without geoclue, so if you don't need it: ... [redshift] location-provider=manual [manual] lat=4.321 ; your location latitude lon=1.234 ; your location longitude

I will try it.
Thank you.

**Comment by clefebvre** [comment] 2021-12-27 12:42
In Startup Applications, you can give Redshift a delay to see if it helps.

![image](https://user-images.githubusercontent.com/1138515/147472717-1cab9aef-7330-4af5-96d3-6b9139f46778.png)

I'm closing since it's upstream and not a 20.3 regression.

**Closed as completed by clefebvre** 2021-12-27 12:42 UTC

**Comment by vegam57** [comment] 2021-12-27 12:55
I will try it.
Thank you.
