### ISSUE TITLE
cinnamon: typing with onboard closes the menu

### ISSUE THREAD

**Issue by haggen88** [linuxmint/mint20.3-beta#78] opened 2022-01-01 18:37 UTC
menu@cinnamon.org closes instantly

Steps to reproduce: 

1) Open Onboard
2) Open the menu [click on the search bar] and try typing with Onboard

**Comment by xenopeek** [comment] 2022-01-01 21:48
"Virtual keyboard" is another on-screen keyboard that you should find is already installed. It's in the Accessories category in the menu. Typing with this in the menu does work. How does Virtual keyboard compare with Onboard for you?

**Comment by haggen88** [comment] 2022-01-01 22:18
Virtual keyboard takes up a lot of screen space. I think it is more oriented to something like a tablet.
BTW  ... I checked and it seems that this bug [is not new](https://github.com/linuxmint/cinnamon/issues/8867)

**Comment by smurphos** [comment] 2022-01-02 07:13
It's not new in that Onboard has never been able to work with Cinnamon's menu entry, and from Michael's comment in the not directly related issue below I suspect that can not be fixed.

https://github.com/linuxmint/Cinnamon/issues/6816

**Comment by clefebvre** [comment] 2022-01-02 10:17
Closing since it's not a regression.

Suggestion: We can probably make our own OSK more configurable and more space efficient.

**Closed as completed by clefebvre** 2022-01-02 10:17 UTC
