### ISSUE TITLE
sticky note : The new Note with the + mark on the sticky note

### ISSUE THREAD

**Issue by vegam57** [linuxmint/mint20.3-beta#57] opened 2021-12-20 23:39 UTC
I like LM sticky notes.
Simple and good.

When adding a new note with the + mark,
I want you to bring it to the front
In the current spec it is generated on the back.
I want to avoid interruptions in brainstorming 

![スクリーンショット 2021-12-21 08-34-09](https://user-images.githubusercontent.com/78515193/146846743-0fc4f278-1bc9-4060-869c-e5dbebc0bf20.png)

**Comment by WhosyVox** [comment] 2021-12-21 01:11
Rephrased: Newly spawned sticky notes don't gain focus on creation.

I've reproduced this issue in Mint 20.2 and 20.3 beta.

**Comment by vegam57** [comment] 2021-12-21 01:25
> Rephrased: Newly spawned sticky notes don't gain focus on creation.
> 
> I've reproduced this issue in Mint 20.2 and 20.3 beta.

Thanks
I'm not a native English speaker, so Rephrased is helpful.

**Comment by haggen88** [comment] 2021-12-21 01:51
I hadn't noticed that, it would be useful to have it corrected.

...

@vegam57  If you move the first note [on which you wrote something] to the right, sticky note will remember that change and you won't have this problem since the new notes will always appear in the upper left corner.

**Comment by vegam57** [comment] 2021-12-21 01:57
What you say is "If you move the first note"
It's not my request.

**Comment by haggen88** [comment] 2021-12-21 02:11
I am referring to the note above the others

**Comment by clefebvre** [comment] 2021-12-27 12:51
Fixed in Sticky 1.6.

**Closed as completed by clefebvre** 2021-12-27 12:51 UTC

**Comment by vegam57** [comment] 2021-12-27 13:00
Thank you everyone.
